targets:
  $default:
    builders:
      rdf_core|vocabulary_builder:
        enabled: true
        options:
          manifest_asset_path: "lib/src/vocab/manifest.json"
          output_dir: "src/vocab/generated"

builders:
  vocabulary_builder:
    import: "package:rdf_core/vocab_builder.dart"
    builder_factories: ["vocabularyBuilder"]
    build_extensions: {"lib/src/vocab/manifest.json": ["lib/src/vocab/generated/_index.dart"]}
    build_to: source
    auto_apply: dependents