name: rdf_core
description: >-
  A type-safe, modular Dart library for modeling, parsing, and serializing RDF data. Clean separation of RDF and serialization concerns.
version: 0.1.0
homepage: https://github.com/kkalass/rdf_core
environment:
  sdk: ^3.7.0
dev_dependencies:
  test: ^1.21.0
